################################# Default configuration ###################
baseURL = "https://www.oboukary.com/"
title = "Boukary Ouedraogo"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
DefaultContentLanguage = "fr"
# ignore blogdown files
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$",
           "\\.knit\\.md$", "\\.utf8\\.md$"]
# disable language
disableLanguages = []
defaultContentLanguageInSubdir = true
################################# Outputs #################################
# hugo outputs
[outputs]
home = ["HTML","RSS"]
# render unsafe html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[permalinks]
    blog = "/:year/:month/:day/:slug/"


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "defer"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "150px"
last_articles = ["blog","post"]
post_exclus =["Dernières nouvelles","Latest News"]

# Meta data
description = "Dernières publications"
author = "Boukary Ouedraogo"
# Contact Information
mobile = ""
email = "bo.ouedraogo7@gmail.com"
location = "Courbevoie, France"
# contact form action
contact_form_action = "https://formspree.io/f/xjvpzkge" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "G-26T44880RB" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = false
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = false
#expire_days = 2

############################# social site ########################
[[params.social]]
icon = "linkedin" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.linkedin.com/in/oboukary/"

[[params.social]]
icon = "github--v1" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://github.com/oboukary"

[[params.social]]
icon = "twitter-circled--v1" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://twitter.com/Boukary16"

################################ France Language ########################
[Languages.fr]
languageName = "Français"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
# copyright
copyright = "Copyright &copy; {year} [Themefisher](https://themefisher.com) Tous droits réservés"
icons8   = "Icônes provenant de [Icons8](https://icones8.fr/)"

######################### france navigation #############################
# main menu
[[Languages.fr.menu.main]]
name = "Accueil"
URL = "/"
weight = 1

[[Languages.fr.menu.main]]
name = "Blog"
URL = "blog/"
weight = 2

[[Languages.fr.menu.main]]
name = "Projets"
URL = "project/"
weight = 3
[[Languages.fr.menu.main]]
name = "Contact"
URL = "contact/"
weight = 4

[[Languages.fr.menu.main]]
name = "CV"
URL = "cv/resume.pdf"
weight = 5



# footer menu
[[Languages.fr.menu.footer]]
name = "A propos"
URL = "about/"
weight = 1

[[Languages.fr.menu.footer]]
name = "Projets"
URL = "project/"
weight = 2

[[Languages.fr.menu.main]]
name = "Contact"
URL = "contact/"
weight = 3


################################ English Language ########################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
# copyright
copyright = "Copyright &copy; {year} [Themefisher](https://themefisher.com) All Rights Reserved"


######################### english navigation #############################
# main menu
[[Languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 2

[[Languages.en.menu.main]]
name = "Project"
URL = "project"
weight = 3

[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 4


# footer menu
[[Languages.en.menu.footer]]
name = "About"
URL = "about"
weight = 1

[[Languages.en.menu.footer]]
name = "Project"
URL = "project"
weight = 2
[[Languages.en.menu.footer]]
name = "Contact"
URL = "contact/"
weight = 3

############################################################################
#    CV
#
[params.profile]
        enable = true
        name = "Simon Doe"
        tagline = "Senior Software Engineer"
        avatar = "avatar.png"

    [params.contact]
        enable = true
        location = "New York"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "0123 4567 890"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "simon.doe@yourwebsite.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "www.yourwebsite.com"
    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/Angular/React/Vue"
        [[params.skills.list.items]]
        details = "Python/Ruby/PHP"
        [[params.skills.list.items]]
        details = "Node.js/ASP.NET"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"
    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MSc in Computer Science"
        university = "University College London"
        dates = "2010 - 2011"
        [[params.education.list]]
        degree = "BSc Maths and Physics"
        university = "Imperial College London"
        dates = "2007 - 2010"
    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"

    [params.summary]
        enable = true
        text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."

    [params.experience]
        enable = true
        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2019 - Present"
        company = "Google"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "2016 - 2019"
        company = "Apple"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2014 - 2016"
        company = "Dropbox"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2013 - 2014"
        company = "Uber"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2014 - 2016"
        company = "Amazon"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "2013 - 2014"
        company = "Startup"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."
    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."
    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"

    



